---
- name: Ensure UFM container is stopped
  docker_container:
    name: "{{ item.value.container_name }}"
    state: "absent"
  with_dict: "{{ mlnx_ufm_services }}"

# NOTE: Use docker_volume module when dependent upon Ansible 2.4.

- name: Check whether UFM volumes are present
  command: docker volume inspect {{ volume }}
  changed_when: False
  with_subelements:
    - "{{ mlnx_ufm_services }}"
    - volumes
  when: "'/' not in volume"
  failed_when:
    - volume_result.rc != 0
    - "'No such volume' not in volume_result.stderr"
  vars:
    volume: "{{ item.1.split(':')[0] }}"
  register: volume_result

- name: Ensure UFM volumes are absent
  command: docker volume rm {{ volume }}
  with_items: "{{ volume_result.results }}"
  when:
    - not item | skipped
    - item.rc == 0
  vars:
    volume: "{{ item.item.1.split(':')[0] }}"
