---
- name: Ensure oci-systemd-hook is installed
  yum:
    name: oci-systemd-hook
    state: present
  become: true

- name: Include tasks to create UFM container
  include_tasks: create.yml
  with_dict: "{{ mlnx_ufm_services }}"
